const user = {
    name: "John Doe",
    email: "joaopedro@yoli.co",
    avatar: "https://example.com/avatar.https://gravatar.com/avatar/ed2b6cf3c5d7cd8193221c1d18b0eb06?s=400&d=robohash&r=x",
    office: "Mecânico"
};

const mockedModels = [
    {
        "modelId": "1",
        "family": "Forest",
        "brand": "Pesa",
        "modelName": "PTH18",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 45000,
        "insurance": "Full coverage",
        "workHeight": 18,
        "platformHeight": 15,
        "horizontalRange": 12,
        "spearHeight": 20,
        "capacity": 500,
        "dimensionWidth": 2.5,
        "dimensionLength": 6.0,
        "dimensionHeight": 3.0,
        "weight": 3000,
        "type": "Crawler",
        "numberOfEquipments": 10,
        "numberOfAvailableEquipments": 7,
        "numberOfRentedOutEquipments": 3,
        "createdAt": "2023-01-01T00:00:00Z",
        "updatedAt": "2024-01-01T00:00:00Z"
    },
    {
        "modelId": "2",
        "family": "Construction",
        "brand": "BuildMax",
        "modelName": "CMX40",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 55000,
        "insurance": "Basic coverage",
        "workHeight": 20,
        "platformHeight": 17,
        "horizontalRange": 15,
        "spearHeight": 22,
        "capacity": 600,
        "dimensionWidth": 2.8,
        "dimensionLength": 6.5,
        "dimensionHeight": 3.5,
        "weight": 3500,
        "type": "Wheeled",
        "numberOfEquipments": 15,
        "numberOfAvailableEquipments": 10,
        "numberOfRentedOutEquipments": 5,
        "createdAt": "2023-02-01T00:00:00Z",
        "updatedAt": "2024-02-01T00:00:00Z"
    },
    {
        "modelId": "3",
        "family": "Agriculture",
        "brand": "AgroEquip",
        "modelName": "AGX25",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 35000,
        "insurance": "Premium coverage",
        "workHeight": 16,
        "platformHeight": 14,
        "horizontalRange": 10,
        "spearHeight": 18,
        "capacity": 400,
        "dimensionWidth": 2.3,
        "dimensionLength": 5.8,
        "dimensionHeight": 2.8,
        "weight": 2800,
        "type": "Crawler",
        "numberOfEquipments": 8,
        "numberOfAvailableEquipments": 6,
        "numberOfRentedOutEquipments": 2,
        "createdAt": "2023-03-01T00:00:00Z",
        "updatedAt": "2024-03-01T00:00:00Z"
    },
    {
        "modelId": "4",
        "family": "Mining",
        "brand": "MinePro",
        "modelName": "MPX50",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 60000,
        "insurance": "Standard coverage",
        "workHeight": 22,
        "platformHeight": 19,
        "horizontalRange": 17,
        "spearHeight": 24,
        "capacity": 700,
        "dimensionWidth": 3.0,
        "dimensionLength": 7.0,
        "dimensionHeight": 3.8,
        "weight": 4000,
        "type": "Wheeled",
        "numberOfEquipments": 12,
        "numberOfAvailableEquipments": 9,
        "numberOfRentedOutEquipments": 3,
        "createdAt": "2023-04-01T00:00:00Z",
        "updatedAt": "2024-04-01T00:00:00Z"
    },
    {
        "modelId": "5",
        "family": "Industrial",
        "brand": "Industro",
        "modelName": "INDX30",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 50000,
        "insurance": "Full coverage",
        "workHeight": 19,
        "platformHeight": 16,
        "horizontalRange": 13,
        "spearHeight": 21,
        "capacity": 550,
        "dimensionWidth": 2.6,
        "dimensionLength": 6.2,
        "dimensionHeight": 3.2,
        "weight": 3200,
        "type": "Crawler",
        "numberOfEquipments": 20,
        "numberOfAvailableEquipments": 15,
        "numberOfRentedOutEquipments": 5,
        "createdAt": "2023-05-01T00:00:00Z",
        "updatedAt": "2024-05-01T00:00:00Z"
    },
    {
        "modelId": "6",
        "family": "Warehouse",
        "brand": "WareEquip",
        "modelName": "WHX15",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 25000,
        "insurance": "Basic coverage",
        "workHeight": 10,
        "platformHeight": 8,
        "horizontalRange": 5,
        "spearHeight": 12,
        "capacity": 300,
        "dimensionWidth": 1.8,
        "dimensionLength": 4.5,
        "dimensionHeight": 2.0,
        "weight": 1500,
        "type": "Wheeled",
        "numberOfEquipments": 25,
        "numberOfAvailableEquipments": 20,
        "numberOfRentedOutEquipments": 5,
        "createdAt": "2023-06-01T00:00:00Z",
        "updatedAt": "2024-06-01T00:00:00Z"
    },
    {
        "modelId": "7",
        "family": "Marine",
        "brand": "AquaTech",
        "modelName": "AQX22",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 70000,
        "insurance": "Premium coverage",
        "workHeight": 24,
        "platformHeight": 20,
        "horizontalRange": 18,
        "spearHeight": 26,
        "capacity": 800,
        "dimensionWidth": 3.2,
        "dimensionLength": 7.5,
        "dimensionHeight": 4.0,
        "weight": 4500,
        "type": "Crawler",
        "numberOfEquipments": 6,
        "numberOfAvailableEquipments": 4,
        "numberOfRentedOutEquipments": 2,
        "createdAt": "2023-07-01T00:00:00Z",
        "updatedAt": "2024-07-01T00:00:00Z"
    },
    {
        "modelId": "8",
        "family": "Energy",
        "brand": "EnerMax",
        "modelName": "ENX35",
        "attachment": {
            "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
            "description": "Attachment description example 1",
            "id": "Attachment ID 1"
        },
        "price": 80000,
        "insurance": "Standard coverage",
        "workHeight": 28,
        "platformHeight": 25,
        "horizontalRange": 20,
        "spearHeight": 30,
        "capacity": 900,
        "dimensionWidth": 3.5,
        "dimensionLength": 8.0,
        "dimensionHeight": 4.5,
        "weight": 5000,
        "type": "Wheeled",
        "numberOfEquipments": 8,
        "numberOfAvailableEquipments": 5,
        "numberOfRentedOutEquipments": 3,
        "createdAt": "2023-08-01T00:00:00Z",
        "updatedAt": "2024-08-01T00:00:00Z"
    }
]

const mockedMachines = [
    {
        "equipmentId": "101",
        "modelId": "1",
        "model": {
            "family": "Forest",
            "brand": "Pesa",
            "modelName": "PTH18",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 45000,
            "insurance": "Full coverage",
            "workHeight": 18,
            "platformHeight": 15,
            "horizontalRange": 12,
            "spearHeight": 20,
            "capacity": 500,
            "dimensionWidth": 2.5,
            "dimensionLength": 6.0,
            "dimensionHeight": 3.0,
            "weight": 3000,
            "type": "Crawler"
        },
        "serial": "FSTPTH18-001",
        "year": 2022,
        "hourmeter": 1200,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": false,
        "yoliId": "YOLI12345",
        "createdAt": "2023-01-01T00:00:00Z",
        "updatedAt": "2024-01-01T00:00:00Z",
        "pendingIssues": 5
    },
    {
        "equipmentId": "102",
        "modelId": "2",
        "model": {
            "family": "Construction",
            "brand": "BuildMax",
            "modelName": "CMX40",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 55000,
            "insurance": "Basic coverage",
            "workHeight": 20,
            "platformHeight": 17,
            "horizontalRange": 15,
            "spearHeight": 22,
            "capacity": 600,
            "dimensionWidth": 2.8,
            "dimensionLength": 6.5,
            "dimensionHeight": 3.5,
            "weight": 3500,
            "type": "Wheeled"
        },
        "serial": "CSTCMX40-002",
        "year": 2021,
        "hourmeter": 1500,
        "isAvailable": false,
        "isRentedOut": true,
        "isUnderMaintenance": false,
        "yoliId": "YOLI67890",
        "createdAt": "2023-02-01T00:00:00Z",
        "updatedAt": "2024-02-01T00:00:00Z",
        "pendingIssues": 2
    },
    {
        "equipmentId": "103",
        "modelId": "3",
        "model": {
            "family": "Agriculture",
            "brand": "AgroEquip",
            "modelName": "AGX25",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 35000,
            "insurance": "Premium coverage",
            "workHeight": 16,
            "platformHeight": 14,
            "horizontalRange": 10,
            "spearHeight": 18,
            "capacity": 400,
            "dimensionWidth": 2.3,
            "dimensionLength": 5.8,
            "dimensionHeight": 2.8,
            "weight": 2800,
            "type": "Crawler"
        },
        "serial": "AGRAGX25-003",
        "year": 2023,
        "hourmeter": 800,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": true,
        "yoliId": "YOLI54321",
        "createdAt": "2023-03-01T00:00:00Z",
        "updatedAt": "2024-03-01T00:00:00Z",
        "pendingIssues": 3
    },
    {
        "equipmentId": "104",
        "modelId": "4",
        "model": {
            "family": "Mining",
            "brand": "MinePro",
            "modelName": "MPX50",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 60000,
            "insurance": "Standard coverage",
            "workHeight": 22,
            "platformHeight": 19,
            "horizontalRange": 17,
            "spearHeight": 24,
            "capacity": 700,
            "dimensionWidth": 3.0,
            "dimensionLength": 7.0,
            "dimensionHeight": 3.8,
            "weight": 4000,
            "type": "Wheeled"
        },
        "serial": "MINMPX50-004",
        "year": 2020,
        "hourmeter": 2000,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": false,
        "yoliId": "YOLI98765",
        "createdAt": "2023-04-01T00:00:00Z",
        "updatedAt": "2024-04-01T00:00:00Z",
        "pendingIssues": 1
    },
    {
        "equipmentId": "105",
        "modelId": "5",
        "model": {
            "family": "Industrial",
            "brand": "Industro",
            "modelName": "INDX30",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 50000,
            "insurance": "Full coverage",
            "workHeight": 19,
            "platformHeight": 16,
            "horizontalRange": 13,
            "spearHeight": 21,
            "capacity": 550,
            "dimensionWidth": 2.6,
            "dimensionLength": 6.2,
            "dimensionHeight": 3.2,
            "weight": 3200,
            "type": "Crawler"
        },
        "serial": "INDINDX30-005",
        "year": 2022,
        "hourmeter": 1100,
        "isAvailable": false,
        "isRentedOut": true,
        "isUnderMaintenance": false,
        "yoliId": "YOLI24680",
        "createdAt": "2023-05-01T00:00:00Z",
        "updatedAt": "2024-05-01T00:00:00Z",
        "pendingIssues": 4
    },
    {
        "equipmentId": "106",
        "modelId": "6",
        "model": {
            "family": "Warehouse",
            "brand": "WareEquip",
            "modelName": "WHX15",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 25000,
            "insurance": "Basic coverage",
            "workHeight": 10,
            "platformHeight": 8,
            "horizontalRange": 5,
            "spearHeight": 12,
            "capacity": 300,
            "dimensionWidth": 1.8,
            "dimensionLength": 4.5,
            "dimensionHeight": 2.0,
            "weight": 1500,
            "type": "Wheeled"
        },
        "serial": "WHX15-006",
        "year": 2023,
        "hourmeter": 600,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": true,
        "yoliId": "YOLI13579",
        "createdAt": "2023-06-01T00:00:00Z",
        "updatedAt": "2024-06-01T00:00:00Z",
        "pendingIssues": 3
    },
    {
        "equipmentId": "107",
        "modelId": "7",
        "model": {
            "family": "Marine",
            "brand": "AquaTech",
            "modelName": "AQX22",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 70000,
            "insurance": "Premium coverage",
            "workHeight": 24,
            "platformHeight": 20,
            "horizontalRange": 18,
            "spearHeight": 26,
            "capacity": 800,
            "dimensionWidth": 3.2,
            "dimensionLength": 7.5,
            "dimensionHeight": 4.0,
            "weight": 4500,
            "type": "Crawler"
        },
        "serial": "AQX22-007",
        "year": 2021,
        "hourmeter": 1400,
        "isAvailable": false,
        "isRentedOut": true,
        "isUnderMaintenance": false,
        "yoliId": "YOLI97531",
        "createdAt": "2023-07-01T00:00:00Z",
        "updatedAt": "2024-07-01T00:00:00Z",
        "pendingIssues": 2
    },
    {
        "equipmentId": "108",
        "modelId": "8",
        "model": {
            "family": "Energy",
            "brand": "EnerMax",
            "modelName": "ENX35",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 80000,
            "insurance": "Standard coverage",
            "workHeight": 28,
            "platformHeight": 25,
            "horizontalRange": 20,
            "spearHeight": 30,
            "capacity": 900,
            "dimensionWidth": 3.5,
            "dimensionLength": 8.0,
            "dimensionHeight": 4.5,
            "weight": 5000,
            "type": "Wheeled"
        },
        "serial": "ENX35-008",
        "year": 2020,
        "hourmeter": 1600,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": false,
        "yoliId": "YOLI24681",
        "createdAt": "2023-08-01T00:00:00Z",
        "updatedAt": "2024-08-01T00:00:00Z",
        "pendingIssues": 1
    },
    {
        "equipmentId": "109",
        "modelId": "8",
        "model": {
            "family": "Energy",
            "brand": "EnerMax",
            "modelName": "ENX35",
            "attachment": {
                "link": "https://www.pesaforest.com.br/_next/image?url=%2Fpth18.png&w=828&q=75",
                "description": "Attachment description example 1",
                "id": "Attachment ID 1"
            },
            "price": 80000,
            "insurance": "Standard coverage",
            "workHeight": 28,
            "platformHeight": 25,
            "horizontalRange": 20,
            "spearHeight": 30,
            "capacity": 900,
            "dimensionWidth": 3.5,
            "dimensionLength": 8.0,
            "dimensionHeight": 4.5,
            "weight": 5000,
            "type": "Wheeled"
        },
        "serial": "ENRT35-008",
        "year": 2020,
        "hourmeter": 1600,
        "isAvailable": true,
        "isRentedOut": false,
        "isUnderMaintenance": false,
        "yoliId": "YOLI30094",
        "createdAt": "2023-08-01T00:00:00Z",
        "updatedAt": "2024-08-01T00:00:00Z",
        "pendingIssues": 0
    },
]


export { user, mockedModels, mockedMachines }